name: Add as Contributor

on:
  push:
    branches:
      - main
    paths:
      - 'MEMBERS.md'

jobs:
  add-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine added member and section
        id: get-member
        run: |
          # Get all added lines.
          ADDED_LINES=$(git log -p -n 1 -- MEMBERS.md | grep "^+[^+]")
          # Among the added lines there should be 1 and only 1 added handle. Lets find it!
          # +|  @example     |      |
          GITHUB_HANDLE=$(echo "$ADDED_LINES" | grep -Eo "@[a-zA-Z0-9_-]+")

          # Determine the section (i.e., repo) by looking for the last "##" before the change.
          REPO_NAME=$(cat MEMBERS.md| grep -B999 "$GITHUB_HANDLE" | grep "## " | tail -1 | sed 's/## //')

          if [[ -n "$GITHUB_HANDLE" && -n "$REPO_NAME" ]]; then
            # Remove @ from the handle and store
            GITHUB_HANDLE=${GITHUB_HANDLE//@/}
          else
            echo "Either GITHUB_HANDLE or REPO_NAME is empty. Exiting..."
            exit 1
          fi

          echo "Detected Repository: $REPO_NAME"
          echo "Detected GitHub Handle: $GITHUB_HANDLE"

          # Dont run these for now.
          # Use GitHub API to add user to the repo as a contributor.
          # curl -X PUT \
          #   -H "Authorization: token ${{ secrets.GH_TOKEN_FLEXICHARGE_ADD_CONTRIBUTOR }}" \
          #   -H "Accept: application/vnd.github.v3+json" \
          #   "https://api.github.com/repos/AlexTelon/$REPO_NAME/collaborators/$GITHUB_HANDLE"
